#! /bin/zsh

# It WILL make it at least 1.9x bigger no matter what

if [[ $1 = '-m' ]]; then
  tsc $2 --outFile $3
  uglifyjs $3 -mc --toplevel --in-situ
  node /Users/geez/Documents/JSMess/compiler/compiler.js $3 $3
  uglifyjs $3 -m --toplevel --in-situ
elif [[ $1 = '--minify' ]]; then
  tsc $2 --outFile $3
  uglifyjs $3 -mc --toplevel --in-situ
elif [[ $1 = '--mess' ]]; then
  tsc $2 --outFile $3
  node /Users/geez/Documents/JSMess/compiler/compiler.js $3 $3
  uglifyjs $3 -m --toplevel --in-situ
elif [[ $1 = '-e' ]]; then
  touch tmp.ts
  echo $2 > tmp.ts
  tsc tmp.ts
  uglifyjs tmp.js -mc --toplevel --in-situ
  node /Users/geez/Documents/JSMess/compiler/compiler.js tmp.js $3
  uglifyjs $3 -m --toplevel --in-situ
  rm tmp.js
  rm tmp.ts
elif [[ $1 = '-h' ]]; then
  echo -e "Usage: ./tsmess [option] [input file] [output file]"
  echo "Options:"
  echo "  > -m : mess up transpiled ts and minify transpiled ts with ulgilfyjs and then save the result to specified output file"
  echo "    > --mess : mess up transpiled ts and then save the result to specified output file"
  echo "    > --minify : minify transpiled ts with uglifyjs and then save the result to specified output file"
  echo "  > -e : mess up transpiled ts and minify transpiled ts with ulgilfyjs and then save the result to specified output file but you give one js statement"
  echo "  > -h : help"
fi